{*******************************************************************
 M¢dulo: elementoTAD
 Tipo:   Programa()     Interfaz-Implementacion TAD(X)   Otros()
 Autor/es: David Rozas
 Fecha de actualizaci¢n: 29/11/2003
 Descripci¢n: Unidad que contiene el tipo de datos elemento.

 *******************************************************************}

UNIT ElTad;

{**************************************************************************
**************************************************************************}

     INTERFACE

     CONST
     PRIMERELEM=1;
     ULTIMOELEM=100;

     TYPE
         tElem= PRIMERELEM..ULTIMOELEM;

     IMPLEMENTATION
END.